<?php namespace App\Models;
use App\Classes\ExerciseEntity;
use App\Classes\PromotionEntity;
use CodeIgniter\Model;

class ExerciseAssignmentModel extends Model {
    protected $table = 'exerciseaffectation';
    protected $allowedFields = ['affectationIsoDate', 'idExo', 'idPromotion'];

    public function isExerciseAssigned(ExerciseEntity $e, PromotionEntity $p) {
        // TODO : confirm works well (data really null when no assignment)
        $data = $this->asArray()
            ->where(['idExo' => $e->getId(), 'idPromotion' => $p->getId()])
            ->first();
        return ($data != null);
    }

    public function syncExercises(PromotionEntity $promo) {
        // TODO : if issue of exercises inserting multiple times, may be because here we don't give an id to those who don't have one !
        // TODO : check if works correctly
        $promotionExerciseAffectations = $promo->getExerciseAssignations();
        $submissions = [];

        // 1. sync exercise affectations on the promotion
        foreach ($promotionExerciseAffectations as $exerciseAffectation) {
            $assignmentData = [
                'affectationIsoDate' => $exerciseAffectation['date'],
                'idExo' => $exerciseAffectation['exercise']->getId(),
                'idPromotion' => $promo->getId(),
            ];
            if (isset($exerciseAffectation['id'])) {
                // no id on new exercises, will be autogenerated
                // doing this allows us to not run useless queries on those already in the DB
                $assignmentData['id'] = $exerciseAffectation['id'];
                $submissions[] = ['assignmentId' => $exerciseAffectation['id'], 'submissions' => $exerciseAffectation['submissions']];
            }
            $this->save($assignmentData);
        }

        // 2. sync the exercise submissions list on the promotion
        $model = new SolutionSubmissionModel();
        $model->saveEntities($submissions);
    }

    public function getPromotionExerciseAssignationsArray($promotionId) {
        /*
         * The array is documented in PromotionEntity.php
         */
        // TODO : test if works correctly, enable the boolean in promotionmodel's helper to get all the promotion data...
        $userModel = new UsersModel();
        $exerciseModel = new ExerciseModel();
        $submissionsModel = new SolutionSubmissionModel();
        $exerciseAssignations = [];
        $query = $this->db->query("SELECT * FROM exerciseaffectation  WHERE idPromotion = ?", array($promotionId));


        if ($query != null) {
            foreach ($query->getResultArray() as $affectation) {
                $exerciseAssignation = [];
                $exerciseAssignation['id'] = $affectation['id'];
                $exerciseAssignation['date'] = $affectation['affectationIsoDate'];
                $exerciseAssignation['exercise'] = $exerciseModel->getExercise($affectation['idExo']);
                $exerciseAssignation['assigner'] = $userModel->getUser($exerciseAssignation['exercise']->getCreatedByMail());
                $exerciseAssignation['submissions'] = $submissionsModel->getAssignationSubmissions($exerciseAssignation['id'], $exerciseAssignation['exercise']);
                $exerciseAssignations[] = $exerciseAssignation;
            }
        }
        return $exerciseAssignations;
    }

    public function unassign($assignId) {
        $this->delete($assignId);
    }

    public function isValidAffectationId($assignId) {
        $affectData = $this->asArray()
            ->where(['id' => $assignId])
            ->first();

        return ($affectData != null);
    }

    public function getPromotionIDThatExerciseIsAffectedTo($assignId) {
        return $this->asArray()
            ->where(['id' => $assignId])
            ->first()['idPromotion'];
    }
}